require("settings")
require("plugins")
require("keymaps")
require("autogroups")

require("ts-config")
require("langsp")
require("autocomplete")
require("tele")
require("harpoons")

--require("cs_onenord")
require("cs_tender")
require("cs_lualine")
require("nvimtree")
require("commenter")
require("neoformater")
require("snips")
require("symbol-outline")
